language: node_js

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - nvm install
  - nvm use
  - npm i -g yarn

install:
  - yarn install

script:
  - yarn generate

notifications:
  email:
    on_success: never
    on_failure: change
